# Endereço do banco (porta 5432 e nome dashboard_solar)
spring.datasource.url=jdbc:postgresql://localhost:5432/dashboard_solar

# Usuário e Senha
spring.datasource.username=postgres
spring.datasource.password=1234

# Pede para o Java criar as tabelas automaticamente se elas não existirem
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect